### ISSUE TITLE
Error accessing CDS data despite agreeing to terms and conditions

### ISSUE THREAD

**Issue by wisemuck** [ErikKusch/KrigR#30]
I'm trying to access data from the Copernicus Climate Data Store (CDS), but I'm receiving an error message that states I haven't agreed to the required terms and conditions. However, I already agreed to the terms and conditions when I registered for my CDS account. Here's the error message:

Error : Client has not agreed to the required terms and conditions.http://copernicus-climate.eu/exc/missing-termsClient has not agreed to the required terms and conditions.list(required_terms = list(list(title = "Licence to use Copernicus Products", url = "https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products", reason = "missing")))FALSEclient

I'm unsure why I'm receiving this error message despite having agreed to the terms and conditions. Can someone please help me resolve this issue and access the data I need from the CDS?

This is the UID use API Key I copied from my user profile:

api_user = "1971**"
api_key = "67171b76-52d1-4d47-8a4b-0fdf6d5*****"

**Comment by ManueleBazzichetto** [comment]
Hello, 

since this morning, I also have problems accessing to the Copernicus CDS. Specifically, when I run download_ERA() setting the same API_user and API_key that I have been (successfully) using for days, I get the following error message:

"Error in wf_set_key(user = as.character(API_User), key = as.character(API_Key),  : 
  Could not validate login information."

I think this happens as the credentials for accessing Copernicus CDS are (internally in download_ERA) checked by emcmwfr:::wf_check_login. The error I got is generated when wf_check_login returns FALSE. I tried to run ecmwfr:::wf_check_login(user = as.character(My_API), key = My_Key, service = 'cds') using my credentials outside of download_ERA, and indeed FALSE is returned.

I double-checked whether there are some sorts of problems with my account, and all seem fine. Perhaps a problem from Copernicus CDS side (although I found no related info on their web-site)? 

I am posting about my issue assuming it's related to the one described above. 

Thanks in advance.

**Comment by wisemuck** [comment]
Hello,
My issue has been solved using a solution from [Copernicus Knowledge Base](https://confluence.ecmwf.int/display/CKB/Common+Error+Messages+for+CDS+Requests)

thanks

**Comment by ErikKusch** [comment]
Hiya,

To address the issue faced by @wisemuck: I commend you for having found the solution to this issue on the Copernicus Knowledge Base. That being said, the error message you encountered (https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products) brings you directly to the page where you need to access the terms for use of ERA5-Land products.

I recognise that I probably need to do a better job at communicating the set-up for terms & conditions.

On to the issue encountered by @ManueleBazzichetto: I cannot reproduce the issue. Please let me know if it persists.

**Comment by ManueleBazzichetto** [comment]
Hello, 

unfortunately, after a few days I am still unable to connect to the Copernicus CDS. However, my issue is most probably not related to KrigR (or ecmwfr). I found out that I can't connect to https://cds.climate.copernicus.eu/ only from one of my computers (when I try to access their web-site, I get the mysterious 'Error 403 Frobidden access'), and I am now investigating what causes the issue with the ECMWFR operators.

Thanks a lot @ErikKusch for your prompt support!

Manuele
